
# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# Optional: review and set an exact version to align with your local hugo installation
variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image:
    name: klakegg/hugo:edge-ext-alpine
    entrypoint : ['']
  before_script:
    - git submodule update --init --recursive
  script:
    - hugo --gc --minify
  artifacts:
    paths:
      - public
  only:
    - master
